# Author : amousset <contact@amousset.me>
# modus_operandi.toml variant
# This variant is optimized for users with red-green color
# deficiency (deuteranopia)

inherits = "modus_operandi"

"constant.character.escape" = "magenta"
"comment" = "yellow-cooler"
"function" = "magenta"
"tag" = "magenta"

"ui.cursor" = { fg = "bg-main", bg = "blue-intense" }
"ui.cursor.primary.normal" = { fg = "bg-main", bg = "blue-intense" }

"diagnostic.error" = { underline = { color = "yellow-intense", style = "curl" } }
"diagnostic.warning" = { underline = { color = "magenta-faint", style = "curl" } }
"diagnostic.info" = { underline = { color = "cyan", style = "curl" } }
"diagnostic.hint" = { underline = { color = "zz", style = "curl" } }

error = "yellow-intense"
warning = "magenta-faint"
info = "cyan"
# TODO: find appropriate color
hint = "zz"

[palette]

yellow = "#695500"
yellow-warmer = "#973300"
yellow-cooler = "#77492f"

bg-mode-line-active = "#d0d6ff"
fg-mode-line-active = "#0f0f0f"
border-mode-line-active = "#4f4f74"

modeline-err = "#603a00"
modeline-warning = "#454500"
modeline-info = "#023d92"

# Diffs
bg-added = "#d5d7ff"
bg-added-faint = "#e6e6ff"
bg-added-refine = "#babcef"
bg-added-fringe = "#275acc"
fg-added = "#303099"
fg-added-intense = "#0303cc"

bg-changed = "#eecfdf"
bg-changed-faint = "#f0dde5"
bg-changed-refine = "#e0b0d0"
bg-changed-fringe = "#9f6ab0"
fg-changed = "#6f1343"
fg-changed-intense = "#7f0f9f"

bg-removed = "#f4f099"
bg-removed-faint = "#f6f6b7"
bg-removed-refine = "#ede06f"
bg-removed-fringe = "#c0b200"
fg-removed = "#553d00"
fg-removed-intense = "#7f6f00"
