theme = "github_dark"

[editor]
line-number = "absolute"
mouse = false
bufferline = "multiple"
cursorline = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.statusline]
left = ["mode", "version-control", "file-name"]
